Add multiselect initial implementation
nordeck/matrix-neoboard pull request #287
Opened 2024-01-15 10:36 UTC by maheichyk

**:heavy_check_mark: Checklist**

- [ ] A changeset describing the change and affected packages ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#changelog-and-versioning)).
- [ ] Added or updated documentation.
- [ ] Tests for new functionality and regression tests for bug fixes.
- [ ] Screenshots or videos attached (for UI changes).
- [ ] All your commits have a `Signed-off-by` line in the message ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#dco)).

2024-01-16 16:11 UTC, ahmadkadri commented on src/state/useWhiteboardSlideInstance.test.tsx
> +describe.only('useActiveElements', () => {
only should be removed!

2024-01-16 16:13 UTC, ahmadkadri approved these changes
Just one comment it is look good to go

2024-01-16 16:38 UTC, mgcm requested changes
looks good - copyright year needs adjusting

2024-01-17 07:15 UTC, ahmadkadri approved these changes

2024-01-17 07:46 UTC, mgcm approved these changes

2024-01-17 09:03 UTC, merged