Hide about menu item if the widget is emmbeded
nordeck/matrix-neoboard pull request #588
Opened 2024-09-30 11:36 UTC by ahmadkadri

**:heavy_check_mark: Checklist**

- [ ] A changeset describing the change and affected packages ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#changelog-and-versioning)).
- [ ] Added or updated documentation.
- [ ] Tests for new functionality and regression tests for bug fixes.
- [ ] Screenshots or videos attached (for UI changes).
- [ ] All your commits have a `Signed-off-by` line in the message ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#dco)).

2024-10-01 06:48 UTC, weeman1337 requested changes
:thinking: I am not sure if an environment variable is the way to go. But I am happy to discuss it.

We already pass props to the React SDK app: https://github.com/nordeck/matrix-neoboard/blob/main/packages/react-sdk/src/App.tsx#L23 I would have expected a new prop there, that can then be used to tell the NeoBoard application whether it is embedded. Eventually this can be just another „layout prop” since hiding something is also „layout“? :D

2024-10-01 06:48 UTC, weeman1337 commented on packages/react-sdk/src/components/HelpCenterBar/HelpMenu.tsx
> +  const embedded = getEnvironment('REACT_APP_EMBADDED') === 'true';
Small typo

```suggestion
  const embedded = getEnvironment('REACT_APP_EMBEDDED') === 'true';
```

2024-10-07 16:00 UTC, mgcm commented
> 🤔 I am not sure if an environment variable is the way to go. But I am happy to discuss it.

When I discussed this PR with Ahmad, this was an option we considered as well.

The current status is that we have a couple more env vars that configure the widget, such as `REACT_APP_HELP_CENTER_URL` and `REACT_APP_HOME_SERVER_URL`, so given the low effort of adding yet another env var, it seemed reasonable.

I think having an `embedded` property in LayoutProps is a good option but as we are still discovering what new behaviours we should adjust for in the Widget, maybe this can slide thru as is?

I mean, will `embedded` only affect the canvas layout? Maybe it will have other non-layout related changes associated with it in the future..

Regardless of how it's implemented, what is missing in this PR is the documentation of how this flag affects the widget.

2024-10-08 07:23 UTC, weeman1337 requested changes
Please add a documentation about the env var here https://github.com/nordeck/matrix-neoboard/blob/main/docs/configuration.md

2024-10-09 09:43 UTC, weeman1337 requested changes

2024-10-09 09:43 UTC, weeman1337 commented on docs/configuration.md
> +# Indicate if the widget is embedded in standalone mode
We should document what it means. In particular hide the about button.

2024-10-09 11:26 UTC, weeman1337 approved these changes
Looks good now :+1:

2024-10-09 13:24 UTC, merged