NEO-875 Support selecting, dragging and resizing of element with touch inputs
nordeck/matrix-neoboard pull request #614
Opened 2024-10-23 00:00 UTC by jaller94

Allows to select, move, resize and change the text of elements using touch.

Other than #574, this PR does not break the mouse input.

**:heavy_check_mark: Checklist**

- [ ] A changeset describing the change and affected packages ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#changelog-and-versioning)).
- [ ] Added or updated documentation.
- [ ] Tests for new functionality and regression tests for bug fixes.
- [ ] Screenshots or videos attached (for UI changes).
- [ ] All your commits have a `Signed-off-by` line in the message ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#dco)).

2024-10-24 11:35 UTC, weeman1337 approved these changes
Tested on desktop with Firefox and Chromium. Works :heavy_check_mark: 

Would be great if someone can review it with a real touch device before merge.

Good work @jaller94 !

2024-10-24 15:12 UTC, mgcm requested changes

2024-10-24 15:12 UTC, mgcm commented on packages/react-sdk/src/components/Whiteboard/ElementBehaviors/Selection/DragSelect.test.tsx
> +  it('should render a selection if there is a ponter move and start coordinates', () => {
pointer:)

2024-10-24 15:28 UTC, mgcm commented
Trying this with an actual touch device (iPad 6th gen with iOS 17.7) and I was able to:

- create a new shape by tapping the tool and then the whiteboard
- resize and move a selected shape after creating it by tapping the board (very slow with lagging behind touch point)
- selecting other shapes only works when a shape is already selected (??) and it's very slow (takes one second between tapping and the shape selection becomes active)
- selecting shapes stops working if you delete the selected shape, for example

What didn't work:

- could not create shapes by dragging
- can't change the text, keyboard input is never activated (what is the supposed interaction here? double tap to edit text?)
- can't multi-select by dragging (dragging moves the whole whiteboard)
- can't use other dragging tools like arrows, lines and pencil
- there is no way to activate context-menus (secondary mouse click equivalent)

2024-10-24 22:08 UTC, jaller94 commented on packages/react-sdk/src/components/Whiteboard/ElementBehaviors/Selection/DragSelect.test.tsx
> +  it('should render a selection if there is a ponter move and start coordinates', () => {
```suggestion
  it('should render a selection if there is a pointer move and start coordinates', () => {
```

2024-10-24 22:24 UTC, mgcm approved these changes

2024-10-25 07:48 UTC, weeman1337 approved these changes

2024-10-25 10:06 UTC, merged