NEO-1075: Prevent a shape from being smaller than 2x2 on creation
nordeck/matrix-neoboard pull request #654
Opened 2024-11-28 13:11 UTC by jaller94

We already enforce this minimum size when resizing. Now, it's also enforced while.

I couldn't find the code that enforces the minimum size when reszing. Would be great to use the same code / values / constant here.

**:heavy_check_mark: Checklist**

- [ ] A changeset describing the change and affected packages ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#changelog-and-versioning)).
- [ ] Added or updated documentation.
- [ ] Tests for new functionality and regression tests for bug fixes.
- [ ] Screenshots or videos attached (for UI changes).
- [ ] All your commits have a `Signed-off-by` line in the message ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#dco)).

2024-12-19 11:00 UTC, weeman1337 requested changes

2024-12-19 11:00 UTC, weeman1337 commented on packages/react-sdk/src/components/Whiteboard/Draft/createShape.ts
> +  // `width` and `height` must not be 0.
Since we have a test for it, please extend it to cover this case

2025-01-02 16:41 UTC, mgcm commented on packages/react-sdk/src/components/Whiteboard/Draft/createShape.ts
> +  // `width` and `height` must not be 0.
tests extended.

2025-01-02 16:44 UTC, mgcm commented on packages/react-sdk/src/components/Whiteboard/ElementBehaviors/Text/TextElement.tsx
> +  // foreign object can't have negative dimensions
Added this as the "drag-selection" component uses the Rectangle shape to render and when doing selection dragging, the text element would be frequently rendered with invalid negative dimensions.

2025-01-02 16:48 UTC, mgcm commented on packages/react-sdk/src/state/crdt/documents/elements.ts
> +    width: Joi.number().strict().min(1).required(),
this implicates that loading exported boards or snapshots with invalid shape dimensions will now fail.

2025-01-02 17:06 UTC, mgcm commented on packages/react-sdk/src/components/Whiteboard/Draft/createShape.test.ts
> +      gridCellSize: 20,
updated to match current grid cell size

2025-01-03 17:07 UTC, ahmadkadri approved these changes

2025-01-06 22:03 UTC, merged