NEO-954: "no snapshot available" dialog
nordeck/matrix-neoboard pull request #696
Opened 2024-12-27 23:52 UTC by mgcm

**:heavy_check_mark: Checklist**

- [ ] A changeset describing the change and affected packages ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#changelog-and-versioning)).
- [ ] Added or updated documentation.
- [ ] Tests for new functionality and regression tests for bug fixes.
- [ ] Screenshots or videos attached (for UI changes).
- [ ] All your commits have a `Signed-off-by` line in the message ([more info](https://github.com/nordeck/.github/blob/main/docs/CONTRIBUTING.md#dco)).

2025-01-10 18:36 UTC, HarHarLinks commented on .changeset/eleven-pans-pull.md
> +'@nordeck/matrix-neoboard-react-sdk': patch
this is a feature!
```suggestion
'@nordeck/matrix-neoboard-widget': minor
'@nordeck/matrix-neoboard-react-sdk': minor
```

2025-01-13 08:18 UTC, maheichyk requested changes
Feature looks good to me, I left few questions/comments to the code.

2025-01-13 08:18 UTC, maheichyk commented on packages/react-sdk/src/components/connection-state/ConnectionStateProvider.tsx
> +  }, [snapshotInfo, snapshotLoadDialogOpen, setSnapshotLoadDialogOpen]);
We can use `snapshotInfo.snapshotLoadFailed` in dependencies to save `useEffect` calls.

2025-01-13 08:18 UTC, maheichyk commented on packages/react-sdk/src/state/synchronizedDocumentImpl.ts
> +  private readonly loadingDone = new BehaviorSubject<boolean>(false);
Do we need this second loading subject to describe the behavior? Seems that `loadingSubject` could be just used.

2025-01-13 08:18 UTC, maheichyk commented on packages/react-sdk/src/components/connection-state/SnapshotLoadStateDialog.tsx
> +  const { snapshotLoadDialogOpen } = useSnapshotLoadState();
I actually wonder if we could use an existing whiteboard instance and use it's state to determine snapshot loading failure. Currently we have only `observeIsLoading` that is not enough but can be changed. In this case we will not need to use store for this data.

2025-01-16 23:50 UTC, mgcm commented on packages/react-sdk/src/state/synchronizedDocumentImpl.ts
> +  private readonly loadingDone = new BehaviorSubject<boolean>(false);
you are right. removing it and adjusting the tests to no longer depend on the loading status, as it is not relevant for them.

2025-01-20 13:22 UTC, mgcm commented on packages/react-sdk/src/components/connection-state/SnapshotLoadStateDialog.tsx
> +  const { snapshotLoadDialogOpen } = useSnapshotLoadState();
I think our discussions have addressed this point and we live with this for now?

2025-01-21 07:32 UTC, maheichyk approved these changes

2025-01-21 07:45 UTC, merged